### ISSUE TITLE
`config.assets.compress = true` will produce .gz for images in Rails 4

### ISSUE THREAD

**Issue by tomchentw** [botandrose/sprockets-image_compressor#14]
Has anyone noticed this issue? I think I should create an example.

**Comment by botandrose** [comment]
Doing some issue cleanup here.

I can confirm that it will produce gzipped images, and I agree that ideally it shouldn't, but I don't think that its anything but a minor problem... just some extra disk space usage and cpu utilization when the asset is first compiled.

Closing, but feel free to submit a PR with a fix, or reopen this issue if its a real problem for anyone.

**Comment by tomchentw** [comment]
Thanks for confirmation! But I don't know how to fix this. Should dig into code...

**Comment by tomchentw** [comment]
Sorry, I tried with various combinations and I don't think it's caused by this Gem. Thanks!
