### ISSUE TITLE
Please log the error when PNG compression fails

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [botandrose/sprockets-image_compressor#18]
When precompiling assets on a Windows system I get the error: `sprockets-image_compressor: PNG compression failed... returning original`. There are no errors logged anywhere and I can't manually fail to compress any of the images (manual calls to `pngcrush in_file out_file 2>&1` through cmd). I'm not sure why the compression fails.

I end up with 2 files; one is a corrupted PNG, the other is a gzipped PNG...probably corrupted. The byte size of both the 1st file is 5 bytes, the gzipped is 25 bytes.

**Comment by botandrose** [comment]
Interesting. I don't have access to a Windows system so I won't be able to reproduce this. However, PRs are welcome!

**Comment by JakeTheSnake3p0** [comment]
I've actually tracked the problem down to the fact that `try_system_binary` uses `which #{@name}`, which returns `/cygdrive/c/...` - which returns "no such file or directory". I'd say this isn't truly a problem with your gem, but with my configuration. I'm going to issue a pull request that gives a more detailed response in weird circumstances like this.

**Comment by JakeTheSnake3p0** [comment]
[Pull request made](https://github.com/botandrose/sprockets-image_compressor/pull/19)
