### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by maxrosecollins** [botandrose/sprockets-image_compressor#21]
After adding this to my gemfile and running bundle install what else do I need to do? A initialiser? 

Thanks
Max

**Comment by botandrose** [comment]
If you're adding it to a Rails app, that should be all you need to do. No configuration needed!

**Comment by maxrosecollins** [comment]
Oh okay! Awesome! run `RAILS_ENV=production bundle exec rake assets:precompile` ?

**Comment by botandrose** [comment]
Yeah, that should work for deployment.
