### ISSUE TITLE
Error while compiling jpeg on heroku

### ISSUE THREAD

**Issue by cesarizu** [botandrose/sprockets-image_compressor#22]
While compiling images, pngs are working just fine but when it gets to a jpeg I get the following error:

```
remote:        rake aborted!
remote:        /tmp/build_4b544f25671005f1057ed45cf3b78433/vendor/bundle/ruby/2.0.0/gems/sprockets-image_compressor-0.3.0/lib/sprockets/image_compressor/binary_finder.rb:17:in `message': undefined local variable or method `binary_name' for #<Sprockets::ImageCompressor::BinaryFinder::NotFound:0x007f61442ae570> (NameError)
remote:        from /tmp/build_4b544f25671005f1057ed45cf3b78433/vendor/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/errors.rb:16:in `message'
remote:        from /tmp/build_4b544f25671005f1057ed45cf3b78433/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:222:in `display_exception_message_details'
remote:        from /tmp/build_4b544f25671005f1057ed45cf3b78433/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:209:in `display_exception_details'
remote:        from /tmp/build_4b544f25671005f1057ed45cf3b78433/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:198:in `display_error_message'
remote:        from /tmp/build_4b544f25671005f1057ed45cf3b78433/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:185:in `rescue in standard_exception_handling'
remote:        from /tmp/build_4b544f25671005f1057ed45cf3b78433/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
remote:        from /tmp/build_4b544f25671005f1057ed45cf3b78433/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
remote:        from /tmp/build_4b544f25671005f1057ed45cf3b78433/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
remote:        from vendor/bundle/bin/rake:16:in `load'
remote:        from vendor/bundle/bin/rake:16:in `<main>'
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote: 
remote:  !     Push rejected, failed to compile Ruby app
remote: 
```

I'm using:
- Ruby 2.0.0
- Rails 3.2.19
- sprockets-image_compressor 0.3.0
- Heroku cedar-14

Is there anything I'm missing or that I can do to work around this?

**Comment by botandrose** [comment]
Hi Cesar, can you publish a minimal rails app that reproduces this error so
I can debug?

**Comment by cesarizu** [comment]
I'll see if I can make it replicate locally, since it's only happening on heroku. Or at least I'll create a minimum app that can replicate that on heroku.

**Comment by cesarizu** [comment]
I haven't been able to replicate this on a small test app, I'm thinking it might be something else with my setup. I'll continue investigating and post here anything I find.

**Comment by botandrose** [comment]
Roger that. I'll close this issue then. Feel free to reopen if you are able to reproduce.

**Comment by rakeshrajwar** [comment]
HI @botandrose @cesarizu 

I am getting the above error while trying to pre-compile the assets.

(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host 45.33.115.243: rake exit status: 1
rake stdout: Nothing written
rake stderr: I, [2017-05-21T10:26:30.480338 #32500]  INFO -- : Writing /var/www/freeseoreport/releases/20170521102550/public/assets/AvenirLTStd-Light-c7e512c089a16d18cc3daaa63718f143.otf
I, [2017-05-21T10:26:30.481785 #32500]  INFO -- : Writing /var/www/freeseoreport/releases/20170521102550/public/assets/MTI11248107/Purchased_Fonts/Linotype Fonts/Fonts/Avenir/OpenType CFF Std/AvenirLTStd-Light-c7e512c089a16d18cc3daaa63718f143.otf
I, [2017-05-21T10:26:30.483292 #32500]  INFO -- : Writing /var/www/freeseoreport/releases/20170521102550/public/assets/MTI11248107/Purchased_Fonts/Linotype Fonts/Fonts/Linotype Didot/OpenType TTF Pro/DidotOpenFaceCom-f82f44355d4464f591ca083c089b093a.ttf
I, [2017-05-21T10:26:30.485397 #32500]  INFO -- : Writing /var/www/freeseoreport/releases/20170521102550/public/assets/glyphicons-halflings-regular-b668fc68b7cf521435f96ba7fd6c858a.eot
I, [2017-05-21T10:26:30.486543 #32500]  INFO -- : Writing /var/www/freeseoreport/releases/20170521102550/public/assets/glyphicons-halflings-regular-f879282faae175334a2e5776b833a59b.ttf
I, [2017-05-21T10:26:30.487840 #32500]  INFO -- : Writing /var/www/freeseoreport/releases/20170521102550/public/assets/glyphicons-halflings-regular-75e5879f72c42d4465b2f650f9398ee6.woff
NameError: undefined local variable or method `binary_name' for #<Sprockets::ImageCompressor::BinaryFinder::NotFound:0x000000085cf550>
  /var/www/freeseoreport/shared/bundle/ruby/2.0.0/gems/sprockets-image_compressor-0.3.0/lib/sprockets/image_compressor/binary_finder.rb:17:in `message'
  /var/www/freeseoreport/shared/bundle/ruby/2.0.0/gems/sprockets-2.11.0/lib/sprockets/errors.rb:17:in `message'
  /var/www/freeseoreport/shared/bundle/ruby/2.0.0/gems/airbrake-4.1.0/lib/airbrake/notice.rb:123:in `block in initialize'
  /var/www/freeseoreport/shared/bundle/ruby/2.0.0/gems/airbrake-4.1.0/lib/airbrake/notice.rb:299:in `from_exception'
  /var/www/freeseoreport/shared/bundle/ruby/2.0.0/gems/airbrake-4.1.0/lib/airbrake/notice.rb:286:in `exception_attribute'
  /var/www/freeseoreport/shared/bundle/ruby/2.0.0/gems/airbrake-4.1.0/lib/airbrake/notice.rb:122:in `initialize'
  /var/www/freeseoreport/shared/bundle/ruby/2.0.0/gems/airbrake-4.1.0/lib/airbrake.rb:177:in `new'
  /var/www/freeseoreport/shared/bundle/ruby/2.0.0/gems/airbrake-4.1.0/lib/airbrake.rb:177:in `build_notice_for'
  /var/www/freeseoreport/shared/bundle/ruby/2.0.0/gems/airbrake-4.1.0/lib/airbrake.rb:137:in `notify_or_ignore'
  /var/www/freeseoreport/shared/bundle/ruby/2.0.0/gems/airbrake-4.1.0/lib/airbrake/rake_handler.rb:16:in `display_error_message_with_airbrake'
  /var/www/freeseoreport/shared/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:185:in `rescue in standard_exception_handling'
  /var/www/freeseoreport/shared/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
  /var/www/freeseoreport/shared/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
  /var/www/freeseoreport/shared/bundle/ruby/2.0.0/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
  /var/www/freeseoreport/shared/bundle/ruby/2.0.0/bin/rake:23:in `load'
  /var/www/freeseoreport/shared/bundle/ruby/2.0.0/bin/rake:23:in `<top (required)>'

SSHKit::Command::Failed: rake exit status: 1
rake stdout: Nothing written

Error is NameError: undefined local variable or method `binary_name' for #
If you have idea about, why it's occurring for me ?
