### ISSUE TITLE
Not executing on Heroku asset precompilation?

### ISSUE THREAD

**Issue by ylluminate** [botandrose/sprockets-image_compressor#3]
We're seeing from [Google's Page Speed Online](https://developers.google.com/pagespeed/#url=flareaware.com&mobile=false&rule=OptimizeImages) that some of our pngs are not being compressed down fully.  Obviously it appears as though sprockets-image_compressor is not compressing these to their full extent or perhaps not executing at all on Heroku Cedar.  

Would really appreciate your thoughts and input here to understand how to better test to see if it's being executed.  I'd be happy to get some answers from Heroku support if we can't seem to track down the discrepancy.

**Comment by botandrose** [comment]
Looks to me like its not compressing at all. Are you sure its being loaded in production? Perhaps we could add some logging support to the gem to help understand what's happening.

**Comment by ylluminate** [comment]
Yes, exactly what I'm thinking.  And yes, indeed, it is in production mode.  I'd say the logging would be a great idea to get a feel for what's happening.

**Comment by botandrose** [comment]
if you'd like to try your hand at a pull request, id be happy to work with
you to get it merged. what do you say?

On Wed, Feb 29, 2012 at 2:59 PM, George Plymale <
reply@reply.github.com

**Comment by ylluminate** [comment]
Sure, tell me what to do and I'll give it a shot.  Never really collab'd before this way on here so please fill me in?

**Comment by botandrose** [comment]
Here's a good guide to collaborating: http://help.github.com/fork-a-repo/ Let me know if you have any specific questions.

**Comment by ylluminate** [comment]
Simple enough.  Question for ya': Where does this come into play precisely? During the precompilation phase, correct?  

I pushed some debug output into `railtie.rb`, yet I'm not seeing anything when it get's to the `assets:precompile` phase:
... ```
       Your bundle is complete! It was installed into ./vendor/bundle
       Cleaning up the bundler cache.
-----> Writing config/database.yml to read from DATABASE_URL
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile

```

Am I supposed to see it right here or after this step is complete?  Trying to understand exactly where the entry point into the process happens here.

Also, as it spins through all of the files that are compiled, I see no output of the debug either.  It appears that it's not even entering into `railtie.rb` throughout this process.
```

**Comment by botandrose** [comment]
If you inserted some logging into the railtie, it should print out every time the app boots, which includes during that rake task. If you didn't see it, its probably not loading the gem. What happens when you run the app locally?

**Comment by botandrose** [comment]
Closing... Reopen if you're still having issues, or want to get the logging merged in.
