### ISSUE TITLE
Add pngcrush configuration hooks

### ISSUE THREAD

**Issue by yfeldblum** [botandrose/sprockets-image_compressor#4]
Apply more [pngcrush optimizations](http://en.wikipedia.org/wiki/Pngcrush).

**Comment by botandrose** [comment]
Right now, we're just using the defaults: `pngcrush in.png out.png` I haven't experimented with pngcrush's options much, though. Do you think we should be using different settings by default? Maybe -brute? This also might be a good excuse to implement some configuration hooks.

**Comment by yfeldblum** [comment]
`brute` should not be enabled by default because it is probably slow. It should be offered via a config setting:

```
# config/initializers/sprockets.rb

# Uncomment the following line if you want to enable "brute-force" compression.
# Warning: "brute-force" compression may be very slow.
# config.sprockets.image_compressor.pngcrush.brute = true
```

Likewise, any options that may affect the actual image.

Possibly remove color-correction data, chunk metadata, and text metadata by default, but expose a way to stop that.

```
# config/initializers/sprockets.rb

# Uncomment the following lines if images are being pngcrushed too much.
# config.sprockets.image_compressor.pngcrush.preserve_color_correction_data = true
# config.sprockets.image_compressor.pngcrush.preserve_chunk_metadata = true
# config.sprockets.image_compressor.pngcrush.preserve_text_metadata = true
```

Also document these in the `sprockets-image_compressor` readme.

**Comment by botandrose** [comment]
Renaming to `Add pngcrush configuration hooks.`

This looks good to me. Want to take a stab at it? Even a Pull Request with just the README additions would be awesome.
