### ISSUE TITLE
Please join forces with the author of the image_optim gem ;)

### ISSUE THREAD

**Issue by kristianmandrup** [botandrose/sprockets-image_compressor#5]
https://github.com/toy/image_optim

https://github.com/toy/image_optim/issues/2

It has support for pngcrush and several other image compression tools :)

Cheers!

**Comment by botandrose** [comment]
@kristianmandrup, thinking about this, maybe we could get the best of both worlds by making image_optim an alternative backend that one could opt into. You'd lose heroku compatability, but would gain the advantages of the more and better image compressors in image_optim. What do you think?

**Comment by kristianmandrup** [comment]
Sounds perfect :) if you could just have some kind of config option... and couldn't you then set it up to pre-compress before deployment to heroku? I would assume you could determine the environment somehow and then disable the non-heroku compatible features/functionality?
